Food/Models/BaiViet.cs
namespace ReviewFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public   class BaiViet
    {
        
        public int Id { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
       // public int IdDanhMuc { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgaySua { get; set; }
        public bool TrangThai { get; set; }
        public int IdTaiKhoan { get; set; }
       
        public int DanhMucId { get; set; }

        public   DanhMuc DanhMuc { get; set; }
        public   TaiKhoan TaiKhoan { get; set; }
        
        public   ICollection<DanhGia> DanhGias { get; set; }
        
    }
}

Food/Controllers/BaiVietController.cs
using ReviewFood.Models;
using Microsoft.AspNetCore.Mvc;
using Food.Data;
using AutoMapper;
using Microsoft.EntityFrameworkCore;
using PagedList;
using Grpc.Core;

namespace ReviewFood.Controllers
{
    public class BaiVietController : Controller
    {
     
        // GET: BaiViet

        private readonly ApplicationDbContext db;
        private readonly IWebHostEnvironment _hostEnvironment;
        public BaiVietController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment )
        {
            db = context;
       
            _hostEnvironment = hostEnvironment;
        }
        public ActionResult Index(int id = 0)
        {
            if (TempData["Done"] != null || TempData["Error"] != null)
            {
                ViewBag.Done = TempData["Done"];
                ViewBag.Error = TempData["Error"];
                TempData.Remove("Done");
                TempData.Remove("Error");
            }
            var data = db.BaiViets.Find(id);
            if (data == null)
            {
                return RedirectToAction("Index", "Home");
            }
            object comments = db.DanhGias.Where(d => d.Id == id).ToList();
            ViewBag.Comments = comments;
            return View(data);
        }

        public ActionResult Search(string keywork = "", int page = 1)
        {
            var TinTucs = db.BaiViets.Where(d => d.TieuDe.Contains(keywork) || d.NoiDung.Contains(keywork)).ToPagedList(page,12);
            return View(TinTucs);
        }
        public ActionResult Create()
        {
            ViewBag.DanhMucs = db.DanhMucs.ToList();
            return View();
        }

        // POST: Admin/BaiViet/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BaiViet baiViet, IFormFile img)
        {
            try
            {
                string filename = "";
                if (img != null)
                {
                    filename = Path.GetFileNameWithoutExtension(img.FileName);
                }

                else
                {
                    filename = "";
                }
                if (filename != "")
                {
                    string extension = Path.GetExtension(img.FileName);
                    if (extensionFile(extension) == true)
                    {
                        string fileId = Guid.NewGuid().ToString().Replace("-", "");
       

                        string uploadsFolder = Path.Combine(_hostEnvironment.WebRootPath, "Assets", "Image");
                        string uniqueFileName = fileId + extension;
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                              img.CopyTo(stream);
                        }
                        baiViet.HinhAnh = uniqueFileName;
                    }
                    else
                    {
                        ViewBag.Error = "File không đúng định dạng, hãy điền lại dữ liệu";
                        return View(baiViet);
                    }
                }
                baiViet.TrangThai = false;
                //baiViet.IdTaiKhoan = db.BaiViets.Max(p => p.IdTaiKhoan) + 1;
                baiViet.NgayTao = DateTime.Now;
                baiViet.NgaySua = DateTime.Now;
                db.BaiViets.Add(baiViet);
                db.SaveChanges();
                ViewBag.Done = "Thêm bài viết thành công, xin chờ duyệt";
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }
            ViewBag.DanhMucs = db.DanhMucs.ToList();
            return View(baiViet);
        }
        public bool extensionFile(string extension)
        {
            var st_Exten = extension.ToLower();
            switch (st_Exten)
            {
                case ".jpg":
                    return true;
                case ".jpeg":
                    return true;
                case ".png":
                    return true;
                case ".gif":
                    return true;
                case ".veg":
                    return true;
                default:
                    return false;
            }
        }
    }
}

Food/Views/BaiViet/Create.cshtml
@model ReviewFood.Models.BaiViet

@{
    //Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Create Bài Viết";
    ViewData["TitleHeader"] = "Thêm Bài Viết";
}
<style>
    h1 {
        text-align: center;
    }
</style>
<section class="s-content s-content--top-padding s-content--narrow">
    <h1> Tạo Bài Viết</h1>

    <article class="row entry format-standard">

        <div class="entry__media col-full">
            <div class="card card-primary content">
                <div class="row">

                    @using (Html.BeginForm("Create", "BaiViet", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <hr />
                            <div class="form-group">
                                @Html.LabelFor(model => model.HinhAnh, "Hình Ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <input type="file" name="img" id="file" required />
                                </div>
                            </div>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.TieuDe, "Tiêu Đề", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <hr />
                            <div class="form-group">
                                @Html.LabelFor(model => model.NoiDung, "Nội Dung", htmlAttributes: new { @class = "control-label col-md-2" })

                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.NoiDung, new { @class = "form-control", @id = "editor1" })
                                    @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <hr />
                            <div class="form-group">
                                <div class="col-md-10">
                                    @Html.LabelFor(model => model.DanhMuc, "Danh Mục", htmlAttributes: new { @class = "control-label col-md-2" })
                                    @Html.DropDownListFor(model => model.DanhMucId, new SelectList(ViewBag.DanhMucs, "Id", "TenDanhMuc"), "Tên Danh Mục", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.DanhMucId, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <hr />
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                </div>

                            </div>
                        </div>
                        <div>
                            @Html.ActionLink("Quay trờ lại", "/")
                        </div>
                    }

                </div>
            </div>
        </div>
    </article>

</section>


@section Scripts
{
    @{
        var message_done = ViewBag.Done;
        var message_err = ViewBag.Error;
    }
    <script>
        var message_done = '@Html.Raw(message_done)';
        var message_err = '@Html.Raw(message_err)';
        console.log(message_done)
        if (message_done != "" && message_done != null) {
            toastr.success(message_done, 'Thành công!');
        } else if (message_err != "" && message_err != null) {
            toastr.error(message_err, 'Lỗi!');
        }
        CKEDITOR.replace( 'editor1' );
    </script>
}

Food/Views/BaiViet/Index.cshtml
@model ReviewFood.Models.BaiViet

<section class="s-content s-content--top-padding s-content--narrow">
    <div class="row">
        <div class="column left" style="width: 70%; float: left; padding-right: 2%;">
            <article class="row entry format-standard">

                <div class="entry__media col-full">
                    <div class="entry__post-thumb">
                        <img src="/Assets/Image/@Model.HinhAnh"
                             srcset="/Assets/Image/@Model.HinhAnh"
                             sizes="(max-width: 200px) 10vw, 20px" alt="hinh anhhhhhhhhh">
                    </div>
                </div>
                <div class="entry__header col-full">
                    <h1 class="entry__header-title display-1">
                        @Model.TieuDe
                    </h1>
                    <ul class="entry__header-meta">
                        <li class="date">@Model.NgayTao</li>
                    </ul>
                </div>
            </article> <!-- end entry/article -->

            <div class="col-full entry__main">
                <div class="row s-content__nav img-reponsive" style="height:100%;width:100%">
                    @Html.Raw(Model.NoiDung)
                </div>
            </div> <!-- end s-content__pagenav -->

        </div>  <!--end column left-->


        <div class="column right" style="width: 30%; float: right; position:sticky;  top: 100px; bottom:0;">
            <div class="comments-wrap">
                <div class="row comment-respond">

                    <!-- START respond -->
                    <div id="respond" class="col-full">
                        <h3 class="h2">Thêm bình luận</h3>

                        <form name="contactForm" id="contactForm" method="post" action="/DanhGia/Create" autocomplete="off">
                            <fieldset>
                                <div class="message form-field">
                                    <input type="hidden" name="MaTinTuc" value="@Model.Id" hidden />
                                    <textarea name="cMessage" id="cMessage" class="full-width" placeholder="Nơi bình luận" required></textarea>
                                    <input name="submit" id="submit" class="btn btn--primary btn-wide full-width" value="Thêm bình luận" type="submit">
                                </div>

                            </fieldset>
                        </form> <!-- end form -->

                    </div>
                    <!-- END respond-->

                </div> <!-- end comment-respond -->

                <div id="comments" class="row">
                    <div class="col-full">

                        <!-- START commentlist -->
                        <ol class="commentlist">
                            @foreach (var item in ViewBag.Comments)
                            {
                                <li class="depth-1 comment">
                                    <div class="comment__content">

                                        <div class="comment__info">
                                            <div class="comment__author">@item.TaiKhoan</div>

                                            <div class="comment__meta">
                                                <div class="comment__time">@item.NgayTao</div>
                                                <div class="comment__reply">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="comment__text">
                                            <p>
                                                @item.NoiDung
                                            </p>
                                        </div>

                                    </div>

                                </li><!-- end comment level 1 -->
                            }
                        </ol>
                        <!-- END commentlist -->

                    </div> <!-- end col-full -->

                </div> <!-- end comments -->

            </div> <!-- end comments-wrap -->

        </div>  <!--end column right-->

    </div>
</section>
@section Scripts
{
    @{
        var message_done = ViewBag.Done;
        var message_err = ViewBag.Error;
    }
    <script>
        var message_done = '@Html.Raw(message_done)';
        var message_err = '@Html.Raw(message_err)';
        console.log(message_done)
        if (message_done != "" && message_done != null) {
            toastr.success(message_done, 'Thành công!');
        } else if (message_err != "" && message_err != null) {
            toastr.error(message_err, 'Lỗi!');
        }
    </script>
}

Food/Views/BaiViet/Search.cshtml
@model PagedList.IPagedList<ReviewFood.Models.BaiViet_DanhMuc>
@using PagedList.Mvc
@{
}
<section class="s-content s-content--top-padding">

    <div class="row entries-wrap add-top-padding wide">
        <div class="entries">

            @foreach (var item in Model)
            {
                <article class="col-block">

                    <div class="item-entry" data-aos="zoom-in">
                        <div class="item-entry__thumb">
                            <a href="/BaiViet/Index/@item.MaTinTuc" class="item-entry__thumb-link">
                                <img src="/Assets/Image/@item.HinhAnh"
                                     srcset="/Assets/Image/@item.HinhAnh" alt="">
                            </a>
                        </div>

                        <div class="item-entry__text">
                            <div class="item-entry__cat">
                                <a href="/DanhMuc/Index/@item.MaDanhMuc">@item.DanhMuc</a>
                            </div>

                            <h1 class="item-entry__title">
                                <a href="/BaiViet/Index/@item.MaTinTuc">@item.TieuDe</a>
                            </h1>

                            <div class="item-entry__date">
                                <a href="/BaiViet/Index/@item.MaTinTuc">@item.NgayTao</a>
                            </div>
                        </div>
                    </div> <!-- item-entry -->

                </article> <!-- end article -->
            }

        </div> <!-- end entries -->
    </div> <!-- end entries-wrap -->

    <div class="row pagination-wrap">
        <div class="col-full">
            <nav class="pgn" data-aos="fade-up">
                <ul class="pagination">
                    @if (Model.HasPreviousPage)
                    {
                        <li class="page-item">
                            <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber - 1 })">&laquo;</a>
                        </li>
                    }

                    @for (int i = 1; i <= Model.PageCount; i++)
                    {
                        <li class="page-item @(Model.PageNumber == i ? "active" : "")">
                            <a class="page-link" href="@Url.Action("Index", new { page = i })">@i</a>
                        </li>
                    }

                    @if (Model.HasNextPage)
                    {
                        <li class="page-item">
                            <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber + 1 })">&raquo;</a>
                        </li>
                    }
                </ul>
            </nav>
        </div>
    </div>

</section>

@section Scripts
{
    <script>var link = $('.pagination > li');
        var link_a = $('.pagination > li > a');
        console.log(link)
        console.log(link_a)
        for (let i = 0; i < link.length; i++) {
            if ($(link[i]).hasClass('PagedList-skipToNext')) $(link_a[i]).addClass("pgn__next")
            else if ($(link[i]).hasClass('PagedList-skipToPrevious')) $(link_a[i]).addClass("pgn__prev")
            else $(link_a[i]).addClass("pgn__num")
        }</script>
}